using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(Collider2D))]
public class CoffeeInteractable : MonoBehaviour {
    [Header("Coffee Generation Settings")]
    [Tooltip("Coffee prefabs that can be generated by this interactable.")]
    [SerializeField] private GameObject[] coffeePrefabs = new GameObject[3];

    [Tooltip("Position where the coffee prefab is spawned.")]
    [SerializeField] private Transform spawnPoint;

    [Tooltip("Coffee prefab index to spawn. 0 = first, 1 = second, 2 = third.")]
    [Range(0, 2)]
    [SerializeField] private int specifiedCoffeeIndex = 0;

    [Tooltip("If enabled, spawns a random coffee prefab and ignores the specified index.")]
    [SerializeField] private bool spawnRandomInstead = false;

    [Header("Interaction Settings")]
    [Tooltip("If enabled, this object can only be interacted with once.")]
    [SerializeField] private bool interactOnlyOnce = true;

    [Tooltip("Minimum time that the interaction prompt stays visible, in seconds.")]
    [SerializeField] private float promptDisplayDuration = 2f;

    private bool isPlayerInZone;
    private PlatformerPlayerController currentPlayer;
    private PlayerInputActions inputActions;

    private Coroutine hidePromptCoroutine;
    private float promptShownTime;
    private bool hasInteracted;

    private void Reset() {
        GetComponent<Collider2D>().isTrigger = true;
    }

    private void Awake() {
        inputActions = new PlayerInputActions();
    }

    private void OnEnable() {
        inputActions.Enable();
    }

    private void OnDisable() {
        inputActions.Disable();

        if (hidePromptCoroutine != null) {
            StopCoroutine(hidePromptCoroutine);
            hidePromptCoroutine = null;
        }

        if (isPlayerInZone) {
            InteractPromptController.Instance?.Hide();
        }

        isPlayerInZone = false;
        currentPlayer = null;
    }

    private void OnDestroy() {
        inputActions.Dispose();
    }

    private void Update() {
        if (!isPlayerInZone || currentPlayer == null) {
            return;
        }

        if (interactOnlyOnce && hasInteracted) {
            return;
        }

        if (inputActions.Player.Interact.WasPressedThisFrame()) {
            Interact();
        }
    }

    private void OnTriggerEnter2D(Collider2D other) {
        PlatformerPlayerController player = other.GetComponentInParent<PlatformerPlayerController>();

        if (player == null) {
            return;
        }

        if (interactOnlyOnce && hasInteracted) {
            return;
        }

        isPlayerInZone = true;
        currentPlayer = player;
        promptShownTime = Time.time;

        if (hidePromptCoroutine != null) {
            StopCoroutine(hidePromptCoroutine);
            hidePromptCoroutine = null;
        }

        InteractPromptController.Instance?.Show(transform);
    }

    private void OnTriggerExit2D(Collider2D other) {
        PlatformerPlayerController player = other.GetComponentInParent<PlatformerPlayerController>();

        if (player != null && player == currentPlayer) {
            isPlayerInZone = false;
            currentPlayer = null;

            float elapsed = Time.time - promptShownTime;
            float remaining = promptDisplayDuration - elapsed;

            SchedulePromptHide(remaining);
        }
    }

    private void Interact() {
        hasInteracted = true;

        SpawnCoffee();

        if (interactOnlyOnce) {
            SchedulePromptHide(0f);
        }
    }

    private void SpawnCoffee() {
        if (coffeePrefabs == null || coffeePrefabs.Length == 0) {
            return;
        }

        int indexToSpawn = specifiedCoffeeIndex;
        if (spawnRandomInstead) {
            indexToSpawn = Random.Range(0, coffeePrefabs.Length);
        }

        indexToSpawn = Mathf.Clamp(indexToSpawn, 0, coffeePrefabs.Length - 1);
        GameObject selectedCoffeePrefab = coffeePrefabs[indexToSpawn];

        if (selectedCoffeePrefab != null) {
            Vector3 spawnPos = spawnPoint != null ? spawnPoint.position : transform.position;
            Instantiate(selectedCoffeePrefab, spawnPos, Quaternion.identity);

            // AudioManager.Instance?.PlayOneShot(SoundType.DoorOpen);
        }
    }

    private void SchedulePromptHide(float delay) {
        if (!gameObject.activeInHierarchy) {
            InteractPromptController.Instance?.Hide();
            return;
        }

        if (hidePromptCoroutine != null) {
            StopCoroutine(hidePromptCoroutine);
            hidePromptCoroutine = null;
        }

        if (delay <= 0f) {
            InteractPromptController.Instance?.Hide();
        }
        else {
            hidePromptCoroutine = StartCoroutine(HidePromptAfterDelay(delay));
        }
    }

    private IEnumerator HidePromptAfterDelay(float delay) {
        yield return new WaitForSeconds(delay);

        InteractPromptController.Instance?.Hide();
        hidePromptCoroutine = null;
    }
}
